debug: true
################################################
#                   Database                   #
################################################

mysql:
  host: "47.93.78.245"
  port: 3306
  database: "test111"
  username: "test111"
  password: "test"



################################################
#                      Cost                    #
################################################
use-itemsadder: true
energy-costs:
  COAL_ORE: 1
  IRON_ORE: 5
  GOLD_ORE: 8
  DIAMOND_ORE: 10
  LAPIS_ORE: 3
  REDSTONE_ORE: 3
  itemsadder-custom_ores:zipstone9: 100
################################################
#                  Energy Value                #
################################################
default-energy: 300
default-max-energy: 300
default-regen-rate: 10

################################################
#                    Max Value                 #
################################################
max-values:
  max-energy: 1000        # 最大能量值
  max-regen-rate: 10      # 最大恢复速率

################################################
#                     potion                   #
################################################
healing-potions:
  potion1:
    name: "小型恢复药水"
    custom-model-data: 1001
    type: "points" # 可选 "points" 或 "percentage"
    amount: 10 # 恢复的具体点数或百分比
  potion2:
    name: "大型恢复药水"
    custom-model-data: 1002
    type: "percentage"
    amount: 25 # 恢复的百分比
  potion3:
    name: "终极恢复药水"
    custom-model-data: 1003
    type: "points"
    amount: 100

################################################
#                    BossBar                   #
################################################

bossbar:
  enabled: true # Whether to enable BossBar display
  display-mode: "permanent" # Options are "permanent" or "temporary"
  display-time: 5 # Time for temporary display (seconds), only valid if display-mode is "temporary"
  title: "&aCurrent Energy: {current_stamina}/{max_stamina}" # Title of the BossBar display
  color: "GREEN" # Color of the BossBar
  style: "SOLID" # Style of the BossBar

# Available colors: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE, LIGHT_BLUE, ORANGE, BROWN, LIGHT_GRAY, GRAY
# Available styles: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20

################################################
#                    Messages                  #
################################################
messages:
  prefix: "&7[&eXiMiningEnergy&7]"
  not-enough-energy: "&cYou don't have enough energy to mine this block!"
  current-energy: "&aYour current energy level is: &e%miningenergy_current_energy%"
  current-energy-err: "&cUnable to retrieve energy level, please try again later."
  energy-upgrade-success: "&aYou get it! Your energy has been upgrade to &{new_max_energy}!"
  upgrade-not-enough-money: "&cYou do not have enough money to upgrade!"
  upgrade-error: "&cAn error occurred while upgrading."
  regen-rate-upgrade-success: "&aYour energy regen rate has been increased to {new_regen_rate} per minute"
  max-limit-reached: "&cYou have reached the maximum limit for this upgrade!"
  low-warning: "&cWarning: Your energy is very low!"
  death-threshold: "&cYou will die due to exhaustion of energy! You should take a break!"
  death: "&cYou have died due to energy exhaustion!"
  death-broadcast: "&c{player} has died due to energy exhaustion!"

  database-active: "&aDatabase connection is active."
  database-not-active: "&cDatabase connection is not active."
  database-name: "&aDatabase name: &b{database_name}"
  database-username: "&aDatabase username: &b{database_username}"
  database-size: "&aDatabase size: &b{database_size}"
  database-size-err: "&cUnable to retrieve database size."
  database-latency: "&aDatabase connection latency &b{latency} &ams."
  database-information-err: "&cError while retrieving database information."

  vault-status: "Vault status: {vault_status}."
  placeholderapi-status: "PlaceholderAPI status: {placeholderapi_status}."
  loaded: "&aLoaded"
  not-loaded: "&cNot Loaded"

  set-max: "&aMax energy set to {new_max_energy} for player {player}."
  set-max-err: "&cAn error occurred while setting max energy."
  set-regen: "&aRegen rate set to {new_regen_rate} for player {player}."
  set-regen-err: "&cAn error occurred while setting regen rate"
  set-current: "&aCurrent energy set to {new_current_energy} for player {player}."
  set-current-err: "&cAn error occurred while setting current energy"
  fill: "&aEnergy filled to max ({max_energy}) for player {player}."
  fill-err: "&cAn error occurred while filling energy."
  setmax-exceeds-limit: "&cCannot set max energy above the limit of {max_energy_limit}!"
  setregen-exceeds-limit: "&cCannot set regen rate above the limit of {max_regen_rate_limit}!"
  addmax-exceeds-limit: "&cCannot increase max energy above the limit of {max_energy_limit}!"
  addmax-success: "&aMax energy increased by {add_value}. New max energy: {new_max_energy}"
  addmax-error: "&cError occurred while increasing max energy."
  addregen-exceeds-limit: "&cCannot increase regen rate above the limit of {max_regen_rate_limit}!"
  addregen-success: "&aRegen rate increased by {add_value}. New regen rate: {new_regen_rate}"
  addregen-error: "&cError occurred while increasing regen rate."
  permission-deny: "&c You do not have permission to use this command!"

  only-player: "&cOnly players can use this command."
  player-not-found: "&cThis player not online or not exist"

  usage: "&cUsage: {command}."
  unknown-command: "&cUnknown command."

  potion-give: "You give player {player} a {potion}!"
  potion-not-found: "Unknown potion {potion}"
  use-potion: "You used {potion}, and your energy has been restored to {current_energy}"



################################################
#                      GUI                     #
################################################
upgrade-gui:
  title: "Upgrade Your Energy"
  size: 27
  buttons:
    10:
      item: "DIAMOND_SWORD"
      custommodeldata: 123456
      name: "Upgrade Energy"
      lore:
        - "Current energy: %miningenergy_current_energy%"
        - "Max energy: %miningenergy_max_energy%"
        - "Cost to upgrade to next level: %miningenergy_upgrade_cost%"
        - "Time to full enerygy: %miningenergy_time_to_full_energy% minutes"
      command: "upgrade"
    12:
      item: "GOLDEN_APPLE"
      custommodeldata: 123457
      name: "Increase Regen Rate"
      lore:
        - "Regen rate: %miningenergy_rate%"
        - "Cost to upgrade to next level: %miningenergy_rate_upgrade_cost%"
      command: "increase_regen_rate"

##        - "当前能量: %miningenergy_current_energy%"
##        - "最大能量: %miningenergy_max_energy%"
##        - "升级需要的金币: %miningenergy_upgrade_cost%"
##        - "速度升级需要： %miningenergy_rate_upgrade_cost%"
##        - "当前恢复速度： %miningenergy_rate%"
##        - "恢复满的时间： %miningenergy_time_to_full_energy%"