name: XiMiningEnergy
version: '${project.version}'
main: cn.hairuosky.ximiningenergy.XiMiningEnergy
api-version: '1.16'
commands:
  miningenergy:
    description: 处理挖矿精力相关命令
    usage: /<command> <status|upgrade>
softdepend:
  - PlaceholderAPI
depend:
  - Vault